# Generated by Django 5.1.1 on 2025-09-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="api_credits_remaining",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of scene API credits remaining"
            ),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="tier",
            field=models.CharField(
                choices=[
                    ("PRO", "Pro"),
                    ("ENTERPRISE", "Enterprise"),
                    ("ENTERPRISE_PERSCENE", "Enterprise Per-Scene"),
                ],
                default="PRO",
                max_length=30,
            ),
        ),
    ]
