# Generated by Django 5.1.1 on 2025-09-16 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_usersubscription_api_credits_remaining_and_more"),
        ("video_processor", "0024_alter_sceneprocessingjob_reconstruction_method"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PerSceneCheckoutSessionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "package",
                    models.CharField(
                        choices=[
                            ("SMALL", "10 Credits - $49.99"),
                            ("MEDIUM", "25 Credits - $114.99"),
                            ("LARGE", "50 Credits - $214.99"),
                            ("BULK", "100 Credits - $399.99"),
                        ],
                        max_length=10,
                    ),
                ),
                ("credits_amount", models.PositiveIntegerField()),
                (
                    "price_cents",
                    models.PositiveIntegerField(help_text="Price in cents"),
                ),
                (
                    "stripe_checkout_session_id",
                    models.CharField(max_length=255, unique=True),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=255),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("credits_added", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perscene_checkouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Per-Scene Checkout Session",
                "verbose_name_plural": "Per-Scene Checkout Sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CreditTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("PURCHASE", "Credit Purchase"),
                            ("REFUND", "Credit Refund"),
                            ("ADJUSTMENT", "Manual Adjustment"),
                            ("CONSUMPTION", "Credit Consumption"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("PACKAGE_PURCHASE", "Package Purchase"),
                            ("TECHNICAL_FAILURE", "Technical Failure"),
                            ("QUALITY_UNSATISFIED", "Unsatisfied with Quality"),
                            ("JOB_DELETED_UNFINISHED", "Job Deleted Before Completion"),
                            ("SCENE_PROCESSING", "Scene Processing"),
                            ("ADMIN_ADJUSTMENT", "Admin Adjustment"),
                            ("ADMIN_REFUND", "Admin Manual Refund"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("FULFILLED", "Fulfilled"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "credits_amount",
                    models.IntegerField(
                        help_text="Credits amount (positive for additions, negative for deductions)"
                    ),
                ),
                (
                    "user_notes",
                    models.TextField(
                        blank=True, help_text="User's notes or request details"
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Admin notes and decision details"
                    ),
                ),
                (
                    "auto_processed",
                    models.BooleanField(
                        default=False, help_text="Was this automatically processed?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("fulfilled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who processed this transaction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_credit_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scene_processing_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_transactions",
                        to="video_processor.sceneprocessingjob",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "checkout_session",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_transaction",
                        to="subscriptions.perscenecheckoutsessionrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit Transaction",
                "verbose_name_plural": "Credit Transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="perscenecheckoutsessionrecord",
            index=models.Index(
                fields=["user", "is_completed"], name="subscriptio_user_id_69b8ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="perscenecheckoutsessionrecord",
            index=models.Index(
                fields=["stripe_checkout_session_id"],
                name="subscriptio_stripe__d6c22b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="perscenecheckoutsessionrecord",
            index=models.Index(
                fields=["created_at"], name="subscriptio_created_80288e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="credittransaction",
            index=models.Index(
                fields=["user", "status"], name="subscriptio_user_id_6dbc0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="credittransaction",
            index=models.Index(
                fields=["transaction_type", "status"],
                name="subscriptio_transac_ed838f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="credittransaction",
            index=models.Index(
                fields=["scene_processing_job"], name="subscriptio_scene_p_fa2c0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="credittransaction",
            index=models.Index(
                fields=["checkout_session"], name="subscriptio_checkou_ccdd62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="credittransaction",
            index=models.Index(
                fields=["created_at"], name="subscriptio_created_485791_idx"
            ),
        ),
    ]
