# Generated by Django 5.1.1 on 2025-09-16 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_add_credit_transaction_and_perscene_checkout"),
        ("video_processor", "0024_alter_sceneprocessingjob_reconstruction_method"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="credittransaction",
            name="reason",
        ),
        migrations.AlterField(
            model_name="credittransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("REFUND", "Credit Refund"),
                    ("ADJUSTMENT", "Manual Adjustment"),
                    ("CONSUMPTION", "Credit Consumption"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="RefundRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("TECHNICAL_FAILURE", "Technical Failure"),
                            ("QUALITY_UNSATISFIED", "Unsatisfied with Quality"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("APPROVED", "Approved"),
                            ("DENIED", "Denied"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="REQUESTED",
                        max_length=20,
                    ),
                ),
                (
                    "credits_requested",
                    models.PositiveIntegerField(
                        default=1, help_text="Number of credits requested for refund"
                    ),
                ),
                (
                    "customer_notes",
                    models.TextField(
                        blank=True, help_text="Customer's explanation of the issue"
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Admin's notes and decision reasoning"
                    ),
                ),
                (
                    "auto_approved",
                    models.BooleanField(
                        default=False, help_text="Was this automatically approved?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "credit_transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refund_request",
                        to="subscriptions.credittransaction",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who processed this request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_refund_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scene_processing_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refund_requests",
                        to="video_processor.sceneprocessingjob",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refund_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Refund Request",
                "verbose_name_plural": "Refund Requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="subscriptio_user_id_d5ed20_idx"
                    ),
                    models.Index(
                        fields=["scene_processing_job"],
                        name="subscriptio_scene_p_3c55ec_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="subscriptio_status_1ea323_idx",
                    ),
                ],
            },
        ),
    ]
