# Generated by Django 5.1.1 on 2025-09-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_add_refund_request_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credittransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("PURCHASE", "Credit Purchase"),
                    ("REFUND", "Credit Refund"),
                    ("ADJUSTMENT", "Manual Adjustment"),
                    ("CONSUMPTION", "Credit Consumption"),
                ],
                max_length=20,
            ),
        ),
    ]
