# Generated by Django 5.1.1 on 2025-09-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0005_alter_credittransaction_transaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="credittransaction",
            name="job_created_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Creation timestamp of the job for audit trail purposes",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="credittransaction",
            name="job_title",
            field=models.CharField(
                blank=True,
                help_text="Title of the job for audit trail purposes",
                max_length=255,
            ),
        ),
    ]
