# Generated by Django 5.1.1 on 2025-07-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title for the alert", max_length=100
                    ),
                ),
                ("message", models.TextField(help_text="Alert message content")),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary (Blue)"),
                            ("secondary", "Secondary (Gray)"),
                            ("success", "Success (Green)"),
                            ("danger", "Danger (Red)"),
                            ("warning", "Warning (Yellow)"),
                            ("info", "Info (Light Blue)"),
                            ("light", "Light"),
                            ("dark", "Dark"),
                        ],
                        default="info",
                        help_text="Bootstrap alert type (determines color)",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this alert should be displayed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Alert",
                "verbose_name_plural": "Site Alerts",
                "ordering": ["-created_at"],
            },
        ),
    ]
