# Generated by Django 5.1.1 on 2025-08-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitealert",
            name="message",
            field=models.TextField(
                help_text="Alert message content. HTML links are supported: use &lt;a href='https://discord.gg/your-invite' target='_blank'&gt;Join our Discord&lt;/a&gt;"
            ),
        ),
    ]
