# Generated by Django 5.1.1 on 2024-09-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_processor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="job_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
