# Generated by Django 5.1.1 on 2024-09-18 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_processor", "0002_video_job_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlyFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_path", models.FileField(upload_to="ply_files/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "video",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ply_file",
                        to="video_processor.video",
                    ),
                ),
            ],
        ),
    ]
