# Generated by Django 5.1.1 on 2024-09-19 17:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_processor", "0003_plyfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="SceneProcessingJob",
            fields=[
                ("title", models.CharField(max_length=255)),
                ("video_file", models.FileField(upload_to="videos/")),
                (
                    "ply_file",
                    models.FileField(blank=True, null=True, upload_to="ply_files/"),
                ),
                (
                    "rq_job_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="PlyFile",
        ),
        migrations.DeleteModel(
            name="Video",
        ),
    ]
