# Generated by Django 5.1.1 on 2024-10-02 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_processor", "0004_sceneprocessingjob_delete_plyfile_delete_video"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sceneprocessingjob",
            name="public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sceneprocessingjob",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
