# Generated by Django 5.1.1 on 2024-10-24 00:30

import video_processor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_processor", "0005_sceneprocessingjob_public_sceneprocessingjob_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="sceneprocessingjob",
            name="camera_data",
            field=models.JSONField(
                blank=True,
                help_text="Contains 'lookAt', 'position', and 'up' vectors.",
                null=True,
                validators=[video_processor.models.validate_camera_data],
            ),
        ),
    ]
