# Generated by Django 5.1.1 on 2024-10-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_processor", "0006_sceneprocessingjob_camera_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="sceneprocessingjob",
            name="preview_image",
            field=models.ImageField(blank=True, null=True, upload_to="preview_images/"),
        ),
    ]
