# Generated by Django 5.1.1 on 2024-11-01 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0007_sceneprocessingjob_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sceneprocessingjob',
            name='example',
            field=models.BooleanField(default=False),
        ),
    ]
