# Generated by Django 5.1.1 on 2024-12-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0008_sceneprocessingjob_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='sceneprocessingjob',
            name='example_sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
