# Generated by Django 5.1.1 on 2024-12-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0009_sceneprocessingjob_example_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sceneprocessingjob',
            name='spz_file',
            field=models.FileField(blank=True, null=True, upload_to='spz_files/'),
        ),
    ]
