# Generated by Django 5.1.1 on 2025-02-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0010_sceneprocessingjob_spz_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='sceneprocessingjob',
            name='allow_as_example',
            field=models.BooleanField(default=False, help_text='Indicates if the user is willing to have this scene featured as an example'),
        ),
    ]
