# Generated by Django 5.1.1 on 2025-02-07 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0011_sceneprocessingjob_allow_as_example'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sceneprocessingjob',
            name='allow_as_example',
            field=models.BooleanField(default=False, verbose_name='Allow as Example'),
        ),
        migrations.AlterField(
            model_name='sceneprocessingjob',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Publicly Accessible'),
        ),
        migrations.AlterField(
            model_name='sceneprocessingjob',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
