# Generated by Django 5.1.1 on 2025-04-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0012_alter_sceneprocessingjob_allow_as_example_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sceneprocessingjob',
            name='remove_background',
            field=models.BooleanField(default=False),
        ),
    ]
