# Generated by Django 5.1.1 on 2025-05-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_processor", "0013_sceneprocessingjob_remove_background"),
    ]

    operations = [
        migrations.AddField(
            model_name="sceneprocessingjob",
            name="equirectangular",
            field=models.BooleanField(default=False, verbose_name="360° Video"),
        ),
    ]
