# Generated by Django 5.1.1 on 2025-05-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_processor", "0014_sceneprocessingjob_equirectangular"),
    ]

    operations = [
        migrations.AddField(
            model_name="sceneprocessingjob",
            name="use_background_sphere",
            field=models.BooleanField(
                default=False, verbose_name="Use Gaussian Fibonacci Sphere"
            ),
        ),
    ]
