# Generated by Django 5.1.1 on 2025-05-06 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_processor", "0015_sceneprocessingjob_use_background_sphere"),
    ]

    operations = [
        migrations.AddField(
            model_name="sceneprocessingjob",
            name="training_max_num_gaussians",
            field=models.PositiveIntegerField(
                default=100000,
                validators=[
                    django.core.validators.MinValueValidator(
                        100000, "Maximum number of Gaussians must be at least 100,000."
                    ),
                    django.core.validators.MaxValueValidator(
                        2000000,
                        "Maximum number of Gaussians must be at most 2,000,000.",
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="sceneprocessingjob",
            name="training_num_steps",
            field=models.PositiveIntegerField(
                default=5000,
                validators=[
                    django.core.validators.MinValueValidator(
                        5000, "Number of steps must be at least 5,000."
                    ),
                    django.core.validators.MaxValueValidator(
                        35000, "Number of steps must be at most 35,000."
                    ),
                ],
            ),
        ),
    ]
