# Generated by Django 5.1.1 on 2025-05-07 17:34

from django.db import migrations

def update_default_values(apps, schema_editor):
    SceneProcessingJob = apps.get_model('video_processor', 'SceneProcessingJob')
    SceneProcessingJob.objects.all().update(
        training_max_num_gaussians=1000000,
        training_num_steps=30000
    )

def reverse_default_values(apps, schema_editor):
    SceneProcessingJob = apps.get_model('video_processor', 'SceneProcessingJob')
    SceneProcessingJob.objects.all().update(
        training_max_num_gaussians=100000,
        training_num_steps=5000
    )

class Migration(migrations.Migration):

    dependencies = [
        (
            "video_processor",
            "0017_alter_sceneprocessingjob_training_max_num_gaussians_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(update_default_values, reverse_default_values),
    ]
