# Generated by Django 5.1.1 on 2025-05-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_processor", "0018_update_default_training_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="sceneprocessingjob",
            name="pilgrim_filter",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "None"),
                    ("_1977", "_1977"),
                    ("aden", "Aden"),
                    ("brannan", "Brannan"),
                    ("brooklyn", "Brooklyn"),
                    ("clarendon", "Clarendon"),
                    ("earlybird", "Earlybird"),
                    ("gingham", "Gingham"),
                    ("hudson", "Hudson"),
                    ("inkwell", "Inkwell"),
                    ("kelvin", "Kelvin"),
                    ("lark", "Lark"),
                    ("lofi", "Lo-Fi"),
                    ("maven", "Maven"),
                    ("mayfair", "Mayfair"),
                    ("moon", "Moon"),
                    ("nashville", "Nashville"),
                    ("perpetua", "Perpetua"),
                    ("reyes", "Reyes"),
                    ("rise", "Rise"),
                    ("slumber", "Slumber"),
                    ("stinson", "Stinson"),
                    ("toaster", "Toaster"),
                    ("valencia", "Valencia"),
                    ("walden", "Walden"),
                    ("willow", "Willow"),
                    ("xpro2", "X-Pro II"),
                ],
                help_text="Apply an Instagram-style filter to all frames before processing",
                max_length=128,
                null=True,
                verbose_name="Instagram-style Filter",
            ),
        ),
    ]
