# Generated by Django 5.1.1 on 2025-05-09 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("video_processor", "0019_sceneprocessingjob_pilgrim_filter"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sceneprocessingjob",
            old_name="pilgrim_filter",
            new_name="pilgram_filter",
        ),
    ]
