# Generated by Django 5.1.1 on 2025-06-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "video_processor",
            "0021_alter_sceneprocessingjob_training_max_num_gaussians_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sceneprocessingjob",
            name="reconstruction_method",
            field=models.CharField(
                choices=[
                    ("glomap", "GLOMAP (Fast) - Recommended for most videos"),
                    ("colmap", "COLMAP (Reliable) - Better for challenging videos"),
                ],
                default="glomap",
                help_text="Choose the reconstruction algorithm for creating the 3D point cloud",
                max_length=20,
                verbose_name="3D Reconstruction Method",
            ),
        ),
    ]
