# Generated by Django 5.1.1 on 2025-06-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_processor", "0022_sceneprocessingjob_reconstruction_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sceneprocessingjob",
            name="reconstruction_method",
            field=models.CharField(
                choices=[
                    (
                        "glomap",
                        "GLOMAP - Recommended for most videos. Faster, but more prone to failing",
                    ),
                    (
                        "colmap",
                        "COLMAP - Better for sub-optimal videos. Slower, but more robust",
                    ),
                ],
                default="glomap",
                help_text="Choose the reconstruction algorithm for creating the 3D point cloud",
                max_length=20,
                verbose_name="3D Reconstruction Method",
            ),
        ),
    ]
