# Generated by Django 5.1.1 on 2025-11-07 21:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_processor", "0024_alter_sceneprocessingjob_reconstruction_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="sceneprocessingjob",
            name="apriltag_size_mm",
            field=models.FloatField(
                blank=True,
                help_text="Physical size of AprilTag in millimeters (measured from inner white square). If provided, enables automatic scale calibration (Enterprise only)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1.0, "Tag size must be at least 1mm"
                    ),
                    django.core.validators.MaxValueValidator(
                        1000.0, "Tag size must be at most 1000mm"
                    ),
                ],
                verbose_name="AprilTag Size (mm)",
            ),
        ),
    ]
