# Generated by Django 5.1.1 on 2025-11-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_processor", "0025_sceneprocessingjob_apriltag_size_mm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sceneprocessingjob",
            name="reconstruction_method",
            field=models.CharField(
                choices=[
                    ("glomap", "GLOMAP"),
                    ("colmap", "COLMAP"),
                    ("vggt", "VGGT"),
                    ("quest", "Quest"),
                ],
                default="glomap",
                help_text="Choose the reconstruction algorithm for creating the 3D point cloud",
                max_length=20,
                verbose_name="3D Reconstruction Method",
            ),
        ),
    ]
