# Generated by Django 5.1.1 on 2026-02-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_processor", "0027_alter_sceneprocessingjob_reconstruction_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="sceneprocessingjob",
            name="sog_file",
            field=models.FileField(
                blank=True,
                help_text="Points to meta.json of unbundled SOG directory",
                null=True,
                upload_to="sog_files/",
            ),
        ),
    ]
