# Generated by Django 5.1.1 on 2026-02-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_processor", "0028_sceneprocessingjob_sog_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="sceneprocessingjob",
            name="lod_file",
            field=models.FileField(
                blank=True,
                help_text="Points to lod-meta.json of LOD octree directory",
                null=True,
                upload_to="lod_files/",
            ),
        ),
    ]
