# Generated by Django 5.1.1 on 2026-02-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_processor", "0029_sceneprocessingjob_lod_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sceneprocessingjob",
            name="reconstruction_method",
            field=models.CharField(
                choices=[
                    ("glomap", "GLOMAP"),
                    ("colmap", "COLMAP"),
                    ("vggt", "VGGT"),
                    ("quest", "QUEST"),
                    ("generate_lod", "GENERATE_LOD"),
                ],
                default="glomap",
                help_text="Choose the reconstruction algorithm for creating the 3D point cloud",
                max_length=20,
                verbose_name="3D Reconstruction Method",
            ),
        ),
    ]
