"""
Django settings for vid2scene_server project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
import sentry_sdk

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
dotenv_path = os.path.join(BASE_DIR, '.env')
if os.path.exists(dotenv_path):
    print("Loading environment variables from .env file")
    load_dotenv(dotenv_path)

# Helper function to get environment variables
def get_env_variable(var_name, default=None):
    try:
        return os.environ[var_name]
    except KeyError:
        if default is not None:
            return default
        error_msg = f"Set the {var_name} environment variable"
        raise ImproperlyConfigured(error_msg)

# Environment setting
ENVIRONMENT = get_env_variable('ENVIRONMENT', 'development')  # Default to development

if ENVIRONMENT == 'production':
    print("\033[91m*****************************************************\033[0m")
    print("\033[91m*****************************************************\033[0m")
    print("\033[91m******** WARNING: RUNNING IN PRODUCTION MODE ********\033[0m")
    print("\033[91m*****************************************************\033[0m")
    print("\033[91m*****************************************************\033[0m")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Production deployments must set SECRET_KEY (no default). Outside production
# we fall back to a clearly-insecure dev key so bare-metal `manage.py` commands
# work without configuration; the prefix makes Django's deployment check flag it.
if ENVIRONMENT == 'production':
    SECRET_KEY = get_env_variable('SECRET_KEY')
else:
    SECRET_KEY = get_env_variable('SECRET_KEY', 'django-insecure-dev-only-set-SECRET_KEY-before-exposing-this-server')

# SECURITY WARNING: don't run with debug turned on in production!
if ENVIRONMENT == 'production':
    DEBUG = False
else:
    DEBUG = True

INTERNAL_IPS = ['127.0.0.1']

ALLOWED_HOSTS = get_env_variable('WEBSITE_HOSTNAME', '').split(',') if ENVIRONMENT == 'production' else []
additional_hosts = get_env_variable('ADDITIONAL_ALLOWED_HOSTS', '').split(',') if ENVIRONMENT == 'production' else []
ALLOWED_HOSTS.extend(additional_hosts)

if ENVIRONMENT == 'production':
    # Use HTTPS properly behind a proxy
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # Ensure that cookies are only sent over HTTPS
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True

    # Define trusted origins for CSRF
    CSRF_TRUSTED_ORIGINS = [
        f"https://{host}" for host in ALLOWED_HOSTS
    ]

    # Additional security settings (optional but recommended)
    SECURE_SSL_REDIRECT = True
    # SECURE_HSTS_SECONDS = 3600  # Adjust as needed
    # SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    # SECURE_HSTS_PRELOAD = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    'django.contrib.humanize',
    "whitenoise.runserver_nostatic",
    "django.contrib.staticfiles",
    "django_rq",
    "video_processor",
    "django_vite",
    "viewer",
    "svraster_webgl_demo",
    "waffle",
    "examples",
    'subscriptions',
    'sorl.thumbnail',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    "user_homebase",
    "user_statistics",
    'storages',
    'anymail',
    'crispy_forms',
    'crispy_bootstrap5',
    'django_guid',
    'rest_framework',
    'rest_framework_api_key',
    'notifications',
    'documentation',
    #'silk',
]

# Rate limiting is enabled in production, disabled in development
RATELIMIT_ENABLE = not DEBUG

if ENVIRONMENT == 'production':
    sentry_dsn = get_env_variable("SENTRY_DSN")
    sentry_sdk.init(
        dsn=sentry_dsn,
        # Add data like request headers and IP for users,
        # see https://docs.sentry.io/platforms/python/data-management/data-collected/ for more info
        send_default_pii=False,
        environment=ENVIRONMENT,
    )

CRISPY_TEMPLATE_PACK = 'bootstrap5'
DEBUG_DOCKER = get_env_variable("DEBUG_DOCKER", "false").lower() == "true"

# Parse Redis connection details once for reuse
if ENVIRONMENT == 'production':
    redis_url = get_env_variable("AZURE_REDIS_CONNECTIONSTRING")
    redis_params = redis_url.split(',')
    redis_host_port = redis_params[0].split(':')
    redis_kwargs = {param.split('=', 1)[0]: param.split('=', 1)[1] for param in redis_params[1:]}

# RQ Queues Configuration
if ENVIRONMENT == 'production':
    RQ_QUEUES = {
        "default": {
            "HOST": redis_host_port[0],
            "PORT": int(redis_host_port[1]),
            "DB": 0,
            "DEFAULT_TIMEOUT": 28800,
            "PASSWORD": redis_kwargs.get("password", None),
            "SSL": redis_kwargs.get("ssl", "False").lower() == "true",
        },
        "high": {
            "HOST": redis_host_port[0],
            "PORT": int(redis_host_port[1]),
            "DB": 0,
            "DEFAULT_TIMEOUT": 28800,
            "PASSWORD": redis_kwargs.get("password", None),
            "SSL": redis_kwargs.get("ssl", "False").lower() == "true",
        },
        "internal": {
            "HOST": redis_host_port[0],
            "PORT": int(redis_host_port[1]),
            "DB": 0,
            "DEFAULT_TIMEOUT": 28800,
            "PASSWORD": redis_kwargs.get("password", None),
            "SSL": redis_kwargs.get("ssl", "False").lower() == "true",
        },
        "enterprise": {
            "HOST": redis_host_port[0],
            "PORT": int(redis_host_port[1]),
            "DB": 0,
            "DEFAULT_TIMEOUT": 28800,
            "PASSWORD": redis_kwargs.get("password", None),
            "SSL": redis_kwargs.get("ssl", "False").lower() == "true",
        },
    }
else:
    # Host/port are overridable (REDIS_HOST / REDIS_PORT) so the same dev config
    # works on bare metal and inside the self-host Docker Compose stack.
    redis_host = get_env_variable("REDIS_HOST", "127.0.0.1")
    redis_port = int(get_env_variable("REDIS_PORT", "6379"))
    _dev_queue = {
        "HOST": redis_host,
        "PORT": redis_port,
        "DB": 0,
        "DEFAULT_TIMEOUT": 28800,
        "REDIS_CLIENT_KWARGS": {},
    }
    RQ_QUEUES = {name: dict(_dev_queue) for name in ("default", "high", "internal", "enterprise")}

# Django Cache Configuration (using same Redis as RQ)
if ENVIRONMENT == 'production':
    # Use rediss:// for SSL connections, redis:// for non-SSL
    ssl_enabled = redis_kwargs.get("ssl", "False").lower() == "true"
    protocol = "rediss" if ssl_enabled else "redis"
    
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': f"{protocol}://:{redis_kwargs.get('password', '')}@{redis_host_port[0]}:{redis_host_port[1]}/1",  # Use DB 1 for cache
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': f'redis://{redis_host}:{redis_port}/1',  # Use DB 1 for cache (DB 0 is for RQ)
        }
    }

if ENVIRONMENT == 'production':
    EMAIL_BACKEND = "anymail.backends.sendgrid.EmailBackend"
    DEFAULT_FROM_EMAIL = "noreply@mail2.vid2scene.com"
    ANYMAIL = {
        "SENDGRID_API_KEY": get_env_variable("SENDGRID_API_KEY"),
    }
    # SendGrid template IDs for job notifications
    SENDGRID_JOB_COMPLETION_TEMPLATE_ID = get_env_variable("SENDGRID_JOB_COMPLETION_TEMPLATE_ID")
    SENDGRID_JOB_STATUS_UNSUBSCRIBE_GROUP_ID = int(get_env_variable("SENDGRID_JOB_STATUS_UNSUBSCRIBE_GROUP_ID"))
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    # For development, use placeholder template IDs
    SENDGRID_JOB_COMPLETION_TEMPLATE_ID = "d-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    SENDGRID_JOB_STATUS_UNSUBSCRIBE_GROUP_ID = 000000

# Status notification email
STATUS_EMAIL = get_env_variable("STATUS_EMAIL", "status@example.com")

MIDDLEWARE = [
    'django_guid.middleware.guid_middleware',
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "waffle.middleware.WaffleMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    #"silk.middleware.SilkyMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    'video_processor.middleware.ExceptionLoggingMiddleware',
]

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "optional"
ACCOUNT_AUTHENTICATION_METHOD = "username_email"

ACCOUNT_SIGNUP_FORM_HONEYPOT_FIELD = 'phone_number'

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
]

ROOT_URLCONF = "vid2scene_server.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'django.template.context_processors.request',
                'vid2scene_server.context_processors.google_settings',
                'vid2scene_server.context_processors.site_settings',
                'subscriptions.context_processors.subscription_status',
                'notifications.context_processors.site_alerts',
            ],
        },
    },
]

WSGI_APPLICATION = "vid2scene_server.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

if ENVIRONMENT == 'production':
    conn_str = get_env_variable("AZURE_POSTGRESQL_CONNECTIONSTRING")
    conn_str_params = {pair.split('=')[0]: pair.split('=')[1] for pair in conn_str.split(' ')}
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": conn_str_params['dbname'],
            "USER": conn_str_params['user'],
            "PASSWORD": conn_str_params['password'],
            "HOST": conn_str_params['host'],
            "PORT": conn_str_params['port'],
            "OPTIONS": {
                "sslmode": "require",
            },
        }
    }
elif get_env_variable("POSTGRES_HOST", ""):
    # Self-host / Docker Compose: a real Postgres shared between web and worker.
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": get_env_variable("POSTGRES_DB", "vid2scene"),
            "USER": get_env_variable("POSTGRES_USER", "vid2scene"),
            "PASSWORD": get_env_variable("POSTGRES_PASSWORD", "vid2scene"),
            "HOST": get_env_variable("POSTGRES_HOST"),
            "PORT": get_env_variable("POSTGRES_PORT", "5432"),
        }
    }
else:
    # Bare-metal local development: zero-config SQLite.
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_ROOT = BASE_DIR / "collectedstatic"
STATIC_URL = "/static/"

if ENVIRONMENT == 'production':
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.azure_storage.AzureStorage",
            "OPTIONS": {
                "connection_string": get_env_variable("AZURE_STORAGE_CONNECTIONSTRING"),
                "azure_container": get_env_variable("AZURE_STORAGE_CONTAINER_MEDIA"),
                "timeout": 600,
            },
        },
        "thumbnails": {
            "BACKEND": "storages.backends.azure_storage.AzureStorage",
            "OPTIONS": {
                "connection_string": get_env_variable("AZURE_STORAGE_CONNECTIONSTRING"),
                "azure_container": get_env_variable("AZURE_STORAGE_CONTAINER_THUMBNAILS"),
                "timeout": 600,
            },
        },
    }
else:
    # Azurite (Azure Storage emulator). Host is overridable (AZURITE_HOST) so the
    # same config works on bare metal and in the self-host Docker Compose stack.
    debug_url = get_env_variable("AZURITE_HOST", "127.0.0.1")
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.azure_storage.AzureStorage",
            "OPTIONS": {
                # Azure Storage Emulator / Azurite connection string
                "connection_string": f"DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://{debug_url}:10000/devstoreaccount1;",
                "azure_container": "media",
            },
        },
        "thumbnails": {
            "BACKEND": "storages.backends.azure_storage.AzureStorage",
            "OPTIONS": {
                "connection_string": f"DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://{debug_url}:10000/devstoreaccount1;",
                "azure_container": "thumbnails",
            },
        },
    }

# This is a workaround to allow sorl.thumbnail to use a different storage backend in Django 5.1.
# See https://github.com/jazzband/sorl-thumbnail/issues/748
THUMBNAIL_STORAGE = "video_processor.settings_utils.alias_thumbnail_storage"
from sorl.thumbnail import images
from video_processor.settings_utils import alias_thumbnail_storage
images.get_or_create_storage = alias_thumbnail_storage

# Production uses hashed-manifest static storage for cache busting. That storage
# post-processes every reference inside CSS/JS and FAILS the build if any
# referenced asset is missing, which is brittle for self-hosting. Outside
# production we use plain compressed storage (still gzip/brotli, no strict
# manifest), so `collectstatic` can't fail on a stray missing reference.
STORAGES["staticfiles"] = {
    "BACKEND": (
        "whitenoise.storage.CompressedManifestStaticFilesStorage"
        if ENVIRONMENT == 'production'
        else "whitenoise.storage.CompressedStaticFilesStorage"
    ),
}

# Add COOP/COEP headers for AutoLOD WASM files (required for SharedArrayBuffer/pthreads)
def autolod_add_headers(headers, path, url):
    if '/autolod/' in path or '/autolod64/' in path:
        headers['Cross-Origin-Embedder-Policy'] = 'require-corp'
        headers['Cross-Origin-Resource-Policy'] = 'same-origin'

WHITENOISE_ADD_HEADERS_FUNCTION = autolod_add_headers

# dev_mode=True serves assets from a running Vite dev server (for frontend
# development); dev_mode=False serves the pre-built manifest. Defaults to dev
# outside production, but a self-host container builds the manifest and sets
# VITE_DEV_MODE=false so no Vite dev server is required.
VITE_DEV_MODE = get_env_variable(
    "VITE_DEV_MODE", "true" if ENVIRONMENT != 'production' else "false"
).lower() == "true"

DJANGO_VITE = {
    "default": {
        "dev_mode": VITE_DEV_MODE,
        "manifest_path": BASE_DIR / "viewer" / "static" / "manifest.json"
    },
    "svraster_webgl_demo": {
        # We have to keep this false because it uses webworkers, which doesn't work with django-vite.
        # Therefore, if you're making changes to the submodule, you have to run `npm run build` to rebuild the static files.
        "dev_mode": False,
        "manifest_path": BASE_DIR / "svraster_webgl_demo" / "static" / "manifest_svraster_webgl_demo.json",
        "dev_server_port": 5174,
    }
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

RQ_SHOW_ADMIN_LINK = True

LOGIN_REDIRECT_URL = '/upload/'

DJANGO_GUID = {
    'UUID_LENGTH': 16,
}

DEBUG_LOGGING = get_env_variable("DEBUG_LOGGING", "false").lower() == "true"

LOGGING = {
    "filters": {
        "correlation_id": {
            "()": "django_guid.log_filters.CorrelationId",
        },
    },
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
            "filters": ["correlation_id"],
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "DEBUG" if DEBUG_LOGGING else "INFO",
    },
    "formatters": {
        "verbose": {
            "format": "[{correlation_id}] {levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    'loggers': {
        'django_guid': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    }
}

# PROD_LOCAL means you're connecting to prod, but locally. Not recommended, but needed for 
# urgent debugging in prod from a laptop.
PROD_LOCAL = get_env_variable("PROD_LOCAL", "false").lower() == "true"
RQ_WORKER = get_env_variable("RQ_WORKER", "false").lower() == "true"
if not DEBUG or DEBUG_DOCKER:
    if PROD_LOCAL or RQ_WORKER:
        logfile_path = os.path.join(os.sep, BASE_DIR, "vid2scene_server.log")
    else:
        logfile_path = os.path.join(os.sep, "home", "LogFiles", "vid2scene_server.log")
    
    LOGGING["handlers"]["file"] = {
        "class": "logging.handlers.RotatingFileHandler",
        "filename": logfile_path,
        "maxBytes": 1024*1024*5,  # 5 MB
        "backupCount": 5,
        "level": "DEBUG" if DEBUG_LOGGING else "INFO",
        "formatter": "verbose",
        "filters": ["correlation_id"],
    }
    LOGGING["root"]["handlers"].append("file")
    LOGGING["loggers"]["django_guid"]["handlers"].append("file")

TIME_ZONE = "America/Los_Angeles"

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'user_homebase.authentication.UserAPIKeyAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

if ENVIRONMENT != 'production':
    REST_FRAMEWORK['DEFAULT_RENDERER_CLASSES'] = [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ]

USE_TEST_ASSET_SFM = False

# Billing / subscriptions. Disabled by default for self-hosting: when off, the
# Stripe-backed subscription flow is hidden and every user is granted full
# (unlimited) access. Set BILLING_ENABLED=true and configure Stripe to enable it.
BILLING_ENABLED = get_env_variable("BILLING_ENABLED", "false").lower() == "true"

MAX_VIDEO_FILE_SIZE_FREE = 450 * 1024 * 1024 # 450 MB
MAX_VIDEO_FILE_SIZE_PRO = 1 * 1024 * 1024 * 1024 # 1 GB
MAX_QUEST_FILE_SIZE_FREE = 3 * 1024 * 1024 * 1024 # 3 GB
MAX_QUEST_FILE_SIZE_PRO = 5 * 1024 * 1024 * 1024 # 5 GB

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'EMAIL_AUTHENTICATION': True,
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
GOOGLE_CLIENT_ID = get_env_variable("GOOGLE_CLIENT_ID", "")

# Site URL for building absolute URLs in emails
SITE_URL = get_env_variable("SITE_URL", "https://vid2scene.com") if ENVIRONMENT == 'production' else "http://localhost:8000"

# Public-facing identity / integrations, all overridable via env. Defaults are
# placeholder / empty so a fresh self-host renders no real personal contacts
# and no third-party trackers.
CONTACT_EMAIL = get_env_variable("CONTACT_EMAIL", "contact@example.com")
# Umami analytics: the tracker only renders when a website ID is configured, so
# self-hosters don't phone home to anyone's analytics by default.
UMAMI_WEBSITE_ID = get_env_variable("UMAMI_WEBSITE_ID", "")
UMAMI_SRC = get_env_variable("UMAMI_SRC", "https://cloud.umami.is/script.js")
# Base URL the landing-page hero video is served from (e.g. a CDN). Empty = no
# video (the poster image still shows).
LANDING_VIDEO_BASE_URL = get_env_variable("LANDING_VIDEO_BASE_URL", "")


def should_intercept_request(request):
    """
    Custom intercept function for Django Silk.
    
    Rules:
    - Always profile if user is staff
    - Profile 10% of requests for regular users
    
    Args:
        request: Django HttpRequest object
        
    Returns:
        bool: True if request should be profiled, False otherwise
    """
    # Handle case where user might not be available yet
    # (e.g., before authentication middleware runs)
    if not hasattr(request, 'user'):
        return False
    
    # Always profile staff users
    if request.user.is_staff:
        return True
    
    # Profile 10% of regular user requests
    import random
    return random.random() < 0.10

# SILKY_PYTHON_PROFILER = True
# SILKY_AUTHENTICATION = True  # User must login
# SILKY_AUTHORISATION = True  # User must have permissions
# SILKY_INTERCEPT_FUNC = should_intercept_request
# SILKY_MAX_RECORDED_REQUESTS = 5000
# SILKY_MAX_RECORDED_REQUESTS_CHECK_PERCENT = 20